services:
  - type: web
    name: mashgh-writer-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true
